export const GET_ALL_BOOKS_REQUEST = "GET_ALL_BOOKS_REQUEST";
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS";
export const GET_ALL_BOOKS_FAIL = "GET_ALL_BOOKS_FAIL";

export const GET_RECOMMENDED_BOOKS_REQUEST = "GET_RECOMMENDED_BOOKS_REQUEST";
export const GET_RECOMMENDED_BOOKS_SUCCESS = "GET_RECOMMENDED_BOOKS_SUCCESS";
export const GET_RECOMMENDED_BOOKS_FAIL = "GET_RECOMMENDED_BOOKS_FAIL";

export const GET_BOOK_DETAILS_REQUEST = "GET_BOOK_DETAILS_REQUEST";
export const GET_BOOK_DETAILS_SUCCESS = "GET_BOOK_DETAILS_SUCCESS";
export const GET_BOOK_DETAILS_FAIL = "GET_BOOK_DETAILS_FAIL";