export const GET_BOOK_REVIEWS_REQUEST = "GET_BOOK_REVIEWS_REQUEST";
export const GET_BOOK_REVIEWS_SUCCESS = "GET_BOOK_REVIEWS_SUCCESS";
export const GET_BOOK_REVIEWS_FAIL = "GET_BOOK_REVIEWS_FAIL";

export const SET_REVIEWS_SEARCH_OBJECT = "SET_REVIEWS_SEARCH_OBJECT";

export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";